/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentPermission = IDL.Variant({
  'Viewer' : IDL.Null,
  'Editor' : IDL.Null,
  'NoAccess' : IDL.Null,
  'Owner' : IDL.Null,
});
export const FolderPermission = IDL.Record({
  'grantedAt' : IDL.Int,
  'grantedBy' : IDL.Principal,
  'userId' : IDL.Principal,
  'role' : DocumentPermission,
  'needToKnow' : IDL.Bool,
  'folderId' : IDL.Text,
});
export const AnomalyEvent = IDL.Record({
  'id' : IDL.Text,
  'resolved' : IDL.Bool,
  'detectedAt' : IDL.Int,
  'description' : IDL.Text,
  'isSystemGenerated' : IDL.Bool,
  'affectedFolderId' : IDL.Opt(IDL.Text),
  'severity' : IDL.Text,
  'affectedUserId' : IDL.Opt(IDL.Principal),
  'resolvedBy' : IDL.Opt(IDL.Principal),
  'eventType' : IDL.Text,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'classificationLevel' : IDL.Nat,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'description' : IDL.Text,
  'blobStorageKey' : IDL.Opt(IDL.Text),
  'fileSize' : IDL.Nat,
  'version' : IDL.Nat,
  'folderId' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const Folder = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'sectionId' : IDL.Text,
  'assignedUserId' : IDL.Opt(IDL.Principal),
  'requiredClearanceLevel' : IDL.Nat,
  'isPersonal' : IDL.Bool,
});
export const Section = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'parentSectionId' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'metadata' : IDL.Opt(IDL.Text),
  'body' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
});
export const ExtendedProfile = IDL.Record({
  'clearanceLevel' : IDL.Nat,
  'orgRole' : IDL.Text,
  'name' : IDL.Text,
  'rank' : IDL.Text,
  'isValidatedByCommander' : IDL.Bool,
  'isS2Admin' : IDL.Bool,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'principalId' : IDL.Principal,
  'registered' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'orgRole' : IDL.Text,
  'name' : IDL.Text,
  'rank' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'deleted' : IDL.Bool,
  'subject' : IDL.Text,
  'parentMessageId' : IDL.Opt(IDL.Text),
  'body' : IDL.Text,
  'read' : IDL.Bool,
  'toUserId' : IDL.Principal,
  'sentAt' : IDL.Int,
  'fromUserId' : IDL.Principal,
});
export const PlatformStats = IDL.Record({
  'unresolvedAnomalies' : IDL.Nat,
  'totalFolders' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalDocuments' : IDL.Nat,
  'totalSections' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchSetFolderPermissions' : IDL.Func([IDL.Vec(FolderPermission)], [], []),
  'createAnomalyEvent' : IDL.Func([AnomalyEvent], [IDL.Text], []),
  'createDocument' : IDL.Func([Document], [IDL.Text], []),
  'createFolder' : IDL.Func([Folder], [IDL.Text], []),
  'createSection' : IDL.Func([Section], [IDL.Text], []),
  'createSystemNotification' : IDL.Func([Notification], [], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'deleteFolder' : IDL.Func([IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'deleteSection' : IDL.Func([IDL.Text], [], []),
  'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(ExtendedProfile)], ['query']),
  'getAnomalyEvents' : IDL.Func([], [IDL.Vec(AnomalyEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
  'getDocumentsByFolder' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
  'getFolder' : IDL.Func([IDL.Text], [IDL.Opt(Folder)], ['query']),
  'getFolderPermissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FolderPermission)],
      ['query'],
    ),
  'getFoldersBySection' : IDL.Func([IDL.Text], [IDL.Vec(Folder)], ['query']),
  'getInboxMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMessage' : IDL.Func([IDL.Text], [IDL.Opt(Message)], ['query']),
  'getMyFolderPermission' : IDL.Func(
      [],
      [IDL.Vec(FolderPermission)],
      ['query'],
    ),
  'getMyFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ExtendedProfile)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExtendedProfile)],
      ['query'],
    ),
  'getSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
  'getSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markMessageRead' : IDL.Func([IDL.Text], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'registerProfile' : IDL.Func([ExtendedProfile], [], []),
  'replyToMessage' : IDL.Func([Message], [IDL.Text], []),
  'resolveAnomalyEvent' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'revokeFolderPermission' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([Message], [IDL.Text], []),
  'setFolderPermission' : IDL.Func([FolderPermission], [], []),
  'updateDocument' : IDL.Func([Document], [], []),
  'updateFolder' : IDL.Func([Folder], [], []),
  'updateMyProfile' : IDL.Func([ExtendedProfile], [], []),
  'updateSection' : IDL.Func([Section], [], []),
  'updateUserProfile' : IDL.Func([ExtendedProfile], [], []),
  'validateS2Admin' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentPermission = IDL.Variant({
    'Viewer' : IDL.Null,
    'Editor' : IDL.Null,
    'NoAccess' : IDL.Null,
    'Owner' : IDL.Null,
  });
  const FolderPermission = IDL.Record({
    'grantedAt' : IDL.Int,
    'grantedBy' : IDL.Principal,
    'userId' : IDL.Principal,
    'role' : DocumentPermission,
    'needToKnow' : IDL.Bool,
    'folderId' : IDL.Text,
  });
  const AnomalyEvent = IDL.Record({
    'id' : IDL.Text,
    'resolved' : IDL.Bool,
    'detectedAt' : IDL.Int,
    'description' : IDL.Text,
    'isSystemGenerated' : IDL.Bool,
    'affectedFolderId' : IDL.Opt(IDL.Text),
    'severity' : IDL.Text,
    'affectedUserId' : IDL.Opt(IDL.Principal),
    'resolvedBy' : IDL.Opt(IDL.Principal),
    'eventType' : IDL.Text,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'classificationLevel' : IDL.Nat,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'description' : IDL.Text,
    'blobStorageKey' : IDL.Opt(IDL.Text),
    'fileSize' : IDL.Nat,
    'version' : IDL.Nat,
    'folderId' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const Folder = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'sectionId' : IDL.Text,
    'assignedUserId' : IDL.Opt(IDL.Principal),
    'requiredClearanceLevel' : IDL.Nat,
    'isPersonal' : IDL.Bool,
  });
  const Section = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'parentSectionId' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'metadata' : IDL.Opt(IDL.Text),
    'body' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
  });
  const ExtendedProfile = IDL.Record({
    'clearanceLevel' : IDL.Nat,
    'orgRole' : IDL.Text,
    'name' : IDL.Text,
    'rank' : IDL.Text,
    'isValidatedByCommander' : IDL.Bool,
    'isS2Admin' : IDL.Bool,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'principalId' : IDL.Principal,
    'registered' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'orgRole' : IDL.Text,
    'name' : IDL.Text,
    'rank' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'deleted' : IDL.Bool,
    'subject' : IDL.Text,
    'parentMessageId' : IDL.Opt(IDL.Text),
    'body' : IDL.Text,
    'read' : IDL.Bool,
    'toUserId' : IDL.Principal,
    'sentAt' : IDL.Int,
    'fromUserId' : IDL.Principal,
  });
  const PlatformStats = IDL.Record({
    'unresolvedAnomalies' : IDL.Nat,
    'totalFolders' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalDocuments' : IDL.Nat,
    'totalSections' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchSetFolderPermissions' : IDL.Func([IDL.Vec(FolderPermission)], [], []),
    'createAnomalyEvent' : IDL.Func([AnomalyEvent], [IDL.Text], []),
    'createDocument' : IDL.Func([Document], [IDL.Text], []),
    'createFolder' : IDL.Func([Folder], [IDL.Text], []),
    'createSection' : IDL.Func([Section], [IDL.Text], []),
    'createSystemNotification' : IDL.Func([Notification], [], []),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'deleteFolder' : IDL.Func([IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'deleteSection' : IDL.Func([IDL.Text], [], []),
    'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(ExtendedProfile)], ['query']),
    'getAnomalyEvents' : IDL.Func([], [IDL.Vec(AnomalyEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
    'getDocumentsByFolder' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getFolder' : IDL.Func([IDL.Text], [IDL.Opt(Folder)], ['query']),
    'getFolderPermissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FolderPermission)],
        ['query'],
      ),
    'getFoldersBySection' : IDL.Func([IDL.Text], [IDL.Vec(Folder)], ['query']),
    'getInboxMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMessage' : IDL.Func([IDL.Text], [IDL.Opt(Message)], ['query']),
    'getMyFolderPermission' : IDL.Func(
        [],
        [IDL.Vec(FolderPermission)],
        ['query'],
      ),
    'getMyFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ExtendedProfile)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExtendedProfile)],
        ['query'],
      ),
    'getSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
    'getSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markMessageRead' : IDL.Func([IDL.Text], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'registerProfile' : IDL.Func([ExtendedProfile], [], []),
    'replyToMessage' : IDL.Func([Message], [IDL.Text], []),
    'resolveAnomalyEvent' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'revokeFolderPermission' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([Message], [IDL.Text], []),
    'setFolderPermission' : IDL.Func([FolderPermission], [], []),
    'updateDocument' : IDL.Func([Document], [], []),
    'updateFolder' : IDL.Func([Folder], [], []),
    'updateMyProfile' : IDL.Func([ExtendedProfile], [], []),
    'updateSection' : IDL.Func([Section], [], []),
    'updateUserProfile' : IDL.Func([ExtendedProfile], [], []),
    'validateS2Admin' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };