/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnomalyEvent {
  'id' : string,
  'resolved' : boolean,
  'detectedAt' : bigint,
  'description' : string,
  'isSystemGenerated' : boolean,
  'affectedFolderId' : [] | [string],
  'severity' : string,
  'affectedUserId' : [] | [Principal],
  'resolvedBy' : [] | [Principal],
  'eventType' : string,
}
export interface Document {
  'id' : string,
  'classificationLevel' : bigint,
  'name' : string,
  'mimeType' : string,
  'description' : string,
  'blobStorageKey' : [] | [string],
  'fileSize' : bigint,
  'version' : bigint,
  'folderId' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export type DocumentPermission = { 'Viewer' : null } |
  { 'Editor' : null } |
  { 'NoAccess' : null } |
  { 'Owner' : null };
export interface ExtendedProfile {
  'clearanceLevel' : bigint,
  'orgRole' : string,
  'name' : string,
  'rank' : string,
  'isValidatedByCommander' : boolean,
  'isS2Admin' : boolean,
  'email' : string,
  'avatarUrl' : [] | [string],
  'principalId' : Principal,
  'registered' : boolean,
}
export interface Folder {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'sectionId' : string,
  'assignedUserId' : [] | [Principal],
  'requiredClearanceLevel' : bigint,
  'isPersonal' : boolean,
}
export interface FolderPermission {
  'grantedAt' : bigint,
  'grantedBy' : Principal,
  'userId' : Principal,
  'role' : DocumentPermission,
  'needToKnow' : boolean,
  'folderId' : string,
}
export interface Message {
  'id' : string,
  'deleted' : boolean,
  'subject' : string,
  'parentMessageId' : [] | [string],
  'body' : string,
  'read' : boolean,
  'toUserId' : Principal,
  'sentAt' : bigint,
  'fromUserId' : Principal,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'metadata' : [] | [string],
  'body' : string,
  'userId' : Principal,
  'notificationType' : string,
  'createdAt' : bigint,
  'read' : boolean,
}
export interface PlatformStats {
  'unresolvedAnomalies' : bigint,
  'totalFolders' : bigint,
  'totalMessages' : bigint,
  'totalUsers' : bigint,
  'totalDocuments' : bigint,
  'totalSections' : bigint,
}
export interface Section {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'iconName' : string,
  'parentSectionId' : [] | [string],
}
export interface UserProfile {
  'orgRole' : string,
  'name' : string,
  'rank' : string,
  'email' : string,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchSetFolderPermissions' : ActorMethod<
    [Array<FolderPermission>],
    undefined
  >,
  'createAnomalyEvent' : ActorMethod<[AnomalyEvent], string>,
  'createDocument' : ActorMethod<[Document], string>,
  'createFolder' : ActorMethod<[Folder], string>,
  'createSection' : ActorMethod<[Section], string>,
  'createSystemNotification' : ActorMethod<[Notification], undefined>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'deleteFolder' : ActorMethod<[string], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deleteSection' : ActorMethod<[string], undefined>,
  'getAllFolders' : ActorMethod<[], Array<Folder>>,
  'getAllProfiles' : ActorMethod<[], Array<ExtendedProfile>>,
  'getAnomalyEvents' : ActorMethod<[], Array<AnomalyEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[string], [] | [Document]>,
  'getDocumentsByFolder' : ActorMethod<[string], Array<Document>>,
  'getFolder' : ActorMethod<[string], [] | [Folder]>,
  'getFolderPermissions' : ActorMethod<[string], Array<FolderPermission>>,
  'getFoldersBySection' : ActorMethod<[string], Array<Folder>>,
  'getInboxMessages' : ActorMethod<[], Array<Message>>,
  'getMessage' : ActorMethod<[string], [] | [Message]>,
  'getMyFolderPermission' : ActorMethod<[], Array<FolderPermission>>,
  'getMyFolders' : ActorMethod<[], Array<Folder>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], [] | [ExtendedProfile]>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [ExtendedProfile]>,
  'getSection' : ActorMethod<[string], [] | [Section]>,
  'getSections' : ActorMethod<[], Array<Section>>,
  'getSentMessages' : ActorMethod<[], Array<Message>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markMessageRead' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'registerProfile' : ActorMethod<[ExtendedProfile], undefined>,
  'replyToMessage' : ActorMethod<[Message], string>,
  'resolveAnomalyEvent' : ActorMethod<[string, Principal], undefined>,
  'revokeFolderPermission' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Message], string>,
  'setFolderPermission' : ActorMethod<[FolderPermission], undefined>,
  'updateDocument' : ActorMethod<[Document], undefined>,
  'updateFolder' : ActorMethod<[Folder], undefined>,
  'updateMyProfile' : ActorMethod<[ExtendedProfile], undefined>,
  'updateSection' : ActorMethod<[Section], undefined>,
  'updateUserProfile' : ActorMethod<[ExtendedProfile], undefined>,
  'validateS2Admin' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];