/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AnomalyEvent {
    id: string;
    resolved: boolean;
    detectedAt: bigint;
    description: string;
    isSystemGenerated: boolean;
    affectedFolderId?: string;
    severity: string;
    affectedUserId?: Principal;
    resolvedBy?: Principal;
    eventType: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: string;
    classificationLevel: bigint;
    name: string;
    mimeType: string;
    description: string;
    blobStorageKey?: string;
    fileSize: bigint;
    version: bigint;
    folderId: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface FolderPermission {
    grantedAt: bigint;
    grantedBy: Principal;
    userId: Principal;
    role: DocumentPermission;
    needToKnow: boolean;
    folderId: string;
}
export interface ExtendedProfile {
    clearanceLevel: bigint;
    orgRole: string;
    name: string;
    rank: string;
    isValidatedByCommander: boolean;
    isS2Admin: boolean;
    email: string;
    avatarUrl?: string;
    principalId: Principal;
    registered: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Notification {
    id: string;
    title: string;
    metadata?: string;
    body: string;
    userId: Principal;
    notificationType: string;
    createdAt: bigint;
    read: boolean;
}
export interface Message {
    id: string;
    deleted: boolean;
    subject: string;
    parentMessageId?: string;
    body: string;
    read: boolean;
    toUserId: Principal;
    sentAt: bigint;
    fromUserId: Principal;
}
export interface Folder {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    sectionId: string;
    assignedUserId?: Principal;
    requiredClearanceLevel: bigint;
    isPersonal: boolean;
}
export interface Section {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    iconName: string;
    parentSectionId?: string;
}
export interface PlatformStats {
    unresolvedAnomalies: bigint;
    totalFolders: bigint;
    totalMessages: bigint;
    totalUsers: bigint;
    totalDocuments: bigint;
    totalSections: bigint;
}
export interface UserProfile {
    orgRole: string;
    name: string;
    rank: string;
    email: string;
    avatarUrl?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DocumentPermission {
    Viewer = "Viewer",
    Editor = "Editor",
    NoAccess = "NoAccess",
    Owner = "Owner"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchSetFolderPermissions(permissions: Array<FolderPermission>): Promise<void>;
    createAnomalyEvent(event: AnomalyEvent): Promise<string>;
    createDocument(document: Document): Promise<string>;
    createFolder(folder: Folder): Promise<string>;
    createSection(section: Section): Promise<string>;
    createSystemNotification(notification: Notification): Promise<void>;
    deleteDocument(documentId: string): Promise<void>;
    deleteFolder(folderId: string): Promise<void>;
    deleteMessage(messageId: string): Promise<void>;
    deleteSection(sectionId: string): Promise<void>;
    getAllFolders(): Promise<Array<Folder>>;
    getAllProfiles(): Promise<Array<ExtendedProfile>>;
    getAnomalyEvents(): Promise<Array<AnomalyEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocument(documentId: string): Promise<Document | null>;
    getDocumentsByFolder(folderId: string): Promise<Array<Document>>;
    getFolder(folderId: string): Promise<Folder | null>;
    getFolderPermissions(folderId: string): Promise<Array<FolderPermission>>;
    getFoldersBySection(sectionId: string): Promise<Array<Folder>>;
    getInboxMessages(): Promise<Array<Message>>;
    getMessage(messageId: string): Promise<Message | null>;
    getMyFolderPermission(): Promise<Array<FolderPermission>>;
    getMyFolders(): Promise<Array<Folder>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyProfile(): Promise<ExtendedProfile | null>;
    getPlatformStats(): Promise<PlatformStats>;
    getProfileByPrincipal(user: Principal): Promise<ExtendedProfile | null>;
    getSection(sectionId: string): Promise<Section | null>;
    getSections(): Promise<Array<Section>>;
    getSentMessages(): Promise<Array<Message>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAllNotificationsRead(): Promise<void>;
    markMessageRead(messageId: string): Promise<void>;
    markNotificationRead(notificationId: string): Promise<void>;
    registerProfile(profile: ExtendedProfile): Promise<void>;
    replyToMessage(message: Message): Promise<string>;
    resolveAnomalyEvent(eventId: string, resolvedBy: Principal): Promise<void>;
    revokeFolderPermission(folderId: string, userId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(message: Message): Promise<string>;
    setFolderPermission(permission: FolderPermission): Promise<void>;
    updateDocument(document: Document): Promise<void>;
    updateFolder(folder: Folder): Promise<void>;
    updateMyProfile(profile: ExtendedProfile): Promise<void>;
    updateSection(section: Section): Promise<void>;
    updateUserProfile(profile: ExtendedProfile): Promise<void>;
    validateS2Admin(callerId: Principal): Promise<void>;
}
import type { AnomalyEvent as _AnomalyEvent, Document as _Document, DocumentPermission as _DocumentPermission, ExtendedProfile as _ExtendedProfile, Folder as _Folder, FolderPermission as _FolderPermission, Message as _Message, Notification as _Notification, Section as _Section, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchSetFolderPermissions(arg0: Array<FolderPermission>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchSetFolderPermissions(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchSetFolderPermissions(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createAnomalyEvent(arg0: AnomalyEvent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnomalyEvent(to_candid_AnomalyEvent_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnomalyEvent(to_candid_AnomalyEvent_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDocument(arg0: Document): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(to_candid_Document_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(to_candid_Document_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createFolder(arg0: Folder): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(to_candid_Folder_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(to_candid_Folder_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSection(arg0: Section): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSection(to_candid_Section_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSection(to_candid_Section_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSystemNotification(arg0: Notification): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSystemNotification(to_candid_Notification_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSystemNotification(to_candid_Notification_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteDocument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deleteSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSection(arg0);
            return result;
        }
    }
    async getAllFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFolders();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFolders();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<ExtendedProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnomalyEvents(): Promise<Array<AnomalyEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnomalyEvents();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnomalyEvents();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsByFolder(arg0: string): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByFolder(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByFolder(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFolder(arg0: string): Promise<Folder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFolder(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFolder(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFolderPermissions(arg0: string): Promise<Array<FolderPermission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFolderPermissions(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFolderPermissions(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoldersBySection(arg0: string): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoldersBySection(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoldersBySection(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInboxMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInboxMessages();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInboxMessages();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessage(arg0: string): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFolderPermission(): Promise<Array<FolderPermission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFolderPermission();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFolderPermission();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFolders();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFolders();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<ExtendedProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getProfileByPrincipal(arg0: Principal): Promise<ExtendedProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByPrincipal(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByPrincipal(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSection(arg0: string): Promise<Section | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSection(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSection(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSections(): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSections();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSections();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentMessages();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentMessages();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markMessageRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerProfile(arg0: ExtendedProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(to_candid_ExtendedProfile_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(to_candid_ExtendedProfile_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async replyToMessage(arg0: Message): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToMessage(to_candid_Message_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToMessage(to_candid_Message_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async resolveAnomalyEvent(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAnomalyEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAnomalyEvent(arg0, arg1);
            return result;
        }
    }
    async revokeFolderPermission(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeFolderPermission(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeFolderPermission(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Message): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_Message_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_Message_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setFolderPermission(arg0: FolderPermission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFolderPermission(to_candid_FolderPermission_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFolderPermission(to_candid_FolderPermission_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDocument(arg0: Document): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(to_candid_Document_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(to_candid_Document_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFolder(arg0: Folder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFolder(to_candid_Folder_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFolder(to_candid_Folder_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMyProfile(arg0: ExtendedProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_ExtendedProfile_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_ExtendedProfile_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSection(arg0: Section): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSection(to_candid_Section_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSection(to_candid_Section_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProfile(arg0: ExtendedProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_ExtendedProfile_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_ExtendedProfile_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateS2Admin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateS2Admin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateS2Admin(arg0);
            return result;
        }
    }
}
function from_candid_AnomalyEvent_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnomalyEvent): AnomalyEvent {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentPermission_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentPermission): DocumentPermission {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ExtendedProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedProfile): ExtendedProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_FolderPermission_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FolderPermission): FolderPermission {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Folder_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Folder): Folder {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Section_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Section): Section {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : from_candid_Document_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Folder]): Folder | null {
    return value.length === 0 ? null : from_candid_Folder_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedProfile]): ExtendedProfile | null {
    return value.length === 0 ? null : from_candid_ExtendedProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Section]): Section | null {
    return value.length === 0 ? null : from_candid_Section_n60(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    sectionId: string;
    assignedUserId: [] | [Principal];
    requiredClearanceLevel: bigint;
    isPersonal: boolean;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    sectionId: string;
    assignedUserId?: Principal;
    requiredClearanceLevel: bigint;
    isPersonal: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        sectionId: value.sectionId,
        assignedUserId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.assignedUserId)),
        requiredClearanceLevel: value.requiredClearanceLevel,
        isPersonal: value.isPersonal
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clearanceLevel: bigint;
    orgRole: string;
    name: string;
    rank: string;
    isValidatedByCommander: boolean;
    isS2Admin: boolean;
    email: string;
    avatarUrl: [] | [string];
    principalId: Principal;
    registered: boolean;
}): {
    clearanceLevel: bigint;
    orgRole: string;
    name: string;
    rank: string;
    isValidatedByCommander: boolean;
    isS2Admin: boolean;
    email: string;
    avatarUrl?: string;
    principalId: Principal;
    registered: boolean;
} {
    return {
        clearanceLevel: value.clearanceLevel,
        orgRole: value.orgRole,
        name: value.name,
        rank: value.rank,
        isValidatedByCommander: value.isValidatedByCommander,
        isS2Admin: value.isS2Admin,
        email: value.email,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.avatarUrl)),
        principalId: value.principalId,
        registered: value.registered
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    resolved: boolean;
    detectedAt: bigint;
    description: string;
    isSystemGenerated: boolean;
    affectedFolderId: [] | [string];
    severity: string;
    affectedUserId: [] | [Principal];
    resolvedBy: [] | [Principal];
    eventType: string;
}): {
    id: string;
    resolved: boolean;
    detectedAt: bigint;
    description: string;
    isSystemGenerated: boolean;
    affectedFolderId?: string;
    severity: string;
    affectedUserId?: Principal;
    resolvedBy?: Principal;
    eventType: string;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        detectedAt: value.detectedAt,
        description: value.description,
        isSystemGenerated: value.isSystemGenerated,
        affectedFolderId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.affectedFolderId)),
        severity: value.severity,
        affectedUserId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.affectedUserId)),
        resolvedBy: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.resolvedBy)),
        eventType: value.eventType
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orgRole: string;
    name: string;
    rank: string;
    email: string;
    avatarUrl: [] | [string];
}): {
    orgRole: string;
    name: string;
    rank: string;
    email: string;
    avatarUrl?: string;
} {
    return {
        orgRole: value.orgRole,
        name: value.name,
        rank: value.rank,
        email: value.email,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    classificationLevel: bigint;
    name: string;
    mimeType: string;
    description: string;
    blobStorageKey: [] | [string];
    fileSize: bigint;
    version: bigint;
    folderId: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): {
    id: string;
    classificationLevel: bigint;
    name: string;
    mimeType: string;
    description: string;
    blobStorageKey?: string;
    fileSize: bigint;
    version: bigint;
    folderId: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        classificationLevel: value.classificationLevel,
        name: value.name,
        mimeType: value.mimeType,
        description: value.description,
        blobStorageKey: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.blobStorageKey)),
        fileSize: value.fileSize,
        version: value.version,
        folderId: value.folderId,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grantedAt: bigint;
    grantedBy: Principal;
    userId: Principal;
    role: _DocumentPermission;
    needToKnow: boolean;
    folderId: string;
}): {
    grantedAt: bigint;
    grantedBy: Principal;
    userId: Principal;
    role: DocumentPermission;
    needToKnow: boolean;
    folderId: string;
} {
    return {
        grantedAt: value.grantedAt,
        grantedBy: value.grantedBy,
        userId: value.userId,
        role: from_candid_DocumentPermission_n49(_uploadFile, _downloadFile, value.role),
        needToKnow: value.needToKnow,
        folderId: value.folderId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    deleted: boolean;
    subject: string;
    parentMessageId: [] | [string];
    body: string;
    read: boolean;
    toUserId: Principal;
    sentAt: bigint;
    fromUserId: Principal;
}): {
    id: string;
    deleted: boolean;
    subject: string;
    parentMessageId?: string;
    body: string;
    read: boolean;
    toUserId: Principal;
    sentAt: bigint;
    fromUserId: Principal;
} {
    return {
        id: value.id,
        deleted: value.deleted,
        subject: value.subject,
        parentMessageId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.parentMessageId)),
        body: value.body,
        read: value.read,
        toUserId: value.toUserId,
        sentAt: value.sentAt,
        fromUserId: value.fromUserId
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    metadata: [] | [string];
    body: string;
    userId: Principal;
    notificationType: string;
    createdAt: bigint;
    read: boolean;
}): {
    id: string;
    title: string;
    metadata?: string;
    body: string;
    userId: Principal;
    notificationType: string;
    createdAt: bigint;
    read: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        metadata: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.metadata)),
        body: value.body,
        userId: value.userId,
        notificationType: value.notificationType,
        createdAt: value.createdAt,
        read: value.read
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    iconName: string;
    parentSectionId: [] | [string];
}): {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    iconName: string;
    parentSectionId?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        iconName: value.iconName,
        parentSectionId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.parentSectionId))
    };
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewer: null;
} | {
    Editor: null;
} | {
    NoAccess: null;
} | {
    Owner: null;
}): DocumentPermission {
    return "Viewer" in value ? DocumentPermission.Viewer : "Editor" in value ? DocumentPermission.Editor : "NoAccess" in value ? DocumentPermission.NoAccess : "Owner" in value ? DocumentPermission.Owner : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Folder>): Array<Folder> {
    return value.map((x)=>from_candid_Folder_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExtendedProfile>): Array<ExtendedProfile> {
    return value.map((x)=>from_candid_ExtendedProfile_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnomalyEvent>): Array<AnomalyEvent> {
    return value.map((x)=>from_candid_AnomalyEvent_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FolderPermission>): Array<FolderPermission> {
    return value.map((x)=>from_candid_FolderPermission_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Section>): Array<Section> {
    return value.map((x)=>from_candid_Section_n60(_uploadFile, _downloadFile, x));
}
function to_candid_AnomalyEvent_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnomalyEvent): _AnomalyEvent {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentPermission_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentPermission): _DocumentPermission {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Document_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Document): _Document {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ExtendedProfile_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedProfile): _ExtendedProfile {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_FolderPermission_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FolderPermission): _FolderPermission {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Folder_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Folder): _Folder {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Section_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Section): _Section {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grantedAt: bigint;
    grantedBy: Principal;
    userId: Principal;
    role: DocumentPermission;
    needToKnow: boolean;
    folderId: string;
}): {
    grantedAt: bigint;
    grantedBy: Principal;
    userId: Principal;
    role: _DocumentPermission;
    needToKnow: boolean;
    folderId: string;
} {
    return {
        grantedAt: value.grantedAt,
        grantedBy: value.grantedBy,
        userId: value.userId,
        role: to_candid_DocumentPermission_n13(_uploadFile, _downloadFile, value.role),
        needToKnow: value.needToKnow,
        folderId: value.folderId
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    resolved: boolean;
    detectedAt: bigint;
    description: string;
    isSystemGenerated: boolean;
    affectedFolderId?: string;
    severity: string;
    affectedUserId?: Principal;
    resolvedBy?: Principal;
    eventType: string;
}): {
    id: string;
    resolved: boolean;
    detectedAt: bigint;
    description: string;
    isSystemGenerated: boolean;
    affectedFolderId: [] | [string];
    severity: string;
    affectedUserId: [] | [Principal];
    resolvedBy: [] | [Principal];
    eventType: string;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        detectedAt: value.detectedAt,
        description: value.description,
        isSystemGenerated: value.isSystemGenerated,
        affectedFolderId: value.affectedFolderId ? candid_some(value.affectedFolderId) : candid_none(),
        severity: value.severity,
        affectedUserId: value.affectedUserId ? candid_some(value.affectedUserId) : candid_none(),
        resolvedBy: value.resolvedBy ? candid_some(value.resolvedBy) : candid_none(),
        eventType: value.eventType
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    classificationLevel: bigint;
    name: string;
    mimeType: string;
    description: string;
    blobStorageKey?: string;
    fileSize: bigint;
    version: bigint;
    folderId: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): {
    id: string;
    classificationLevel: bigint;
    name: string;
    mimeType: string;
    description: string;
    blobStorageKey: [] | [string];
    fileSize: bigint;
    version: bigint;
    folderId: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        classificationLevel: value.classificationLevel,
        name: value.name,
        mimeType: value.mimeType,
        description: value.description,
        blobStorageKey: value.blobStorageKey ? candid_some(value.blobStorageKey) : candid_none(),
        fileSize: value.fileSize,
        version: value.version,
        folderId: value.folderId,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    sectionId: string;
    assignedUserId?: Principal;
    requiredClearanceLevel: bigint;
    isPersonal: boolean;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    sectionId: string;
    assignedUserId: [] | [Principal];
    requiredClearanceLevel: bigint;
    isPersonal: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        sectionId: value.sectionId,
        assignedUserId: value.assignedUserId ? candid_some(value.assignedUserId) : candid_none(),
        requiredClearanceLevel: value.requiredClearanceLevel,
        isPersonal: value.isPersonal
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    iconName: string;
    parentSectionId?: string;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    iconName: string;
    parentSectionId: [] | [string];
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        iconName: value.iconName,
        parentSectionId: value.parentSectionId ? candid_some(value.parentSectionId) : candid_none()
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    metadata?: string;
    body: string;
    userId: Principal;
    notificationType: string;
    createdAt: bigint;
    read: boolean;
}): {
    id: string;
    title: string;
    metadata: [] | [string];
    body: string;
    userId: Principal;
    notificationType: string;
    createdAt: bigint;
    read: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        metadata: value.metadata ? candid_some(value.metadata) : candid_none(),
        body: value.body,
        userId: value.userId,
        notificationType: value.notificationType,
        createdAt: value.createdAt,
        read: value.read
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clearanceLevel: bigint;
    orgRole: string;
    name: string;
    rank: string;
    isValidatedByCommander: boolean;
    isS2Admin: boolean;
    email: string;
    avatarUrl?: string;
    principalId: Principal;
    registered: boolean;
}): {
    clearanceLevel: bigint;
    orgRole: string;
    name: string;
    rank: string;
    isValidatedByCommander: boolean;
    isS2Admin: boolean;
    email: string;
    avatarUrl: [] | [string];
    principalId: Principal;
    registered: boolean;
} {
    return {
        clearanceLevel: value.clearanceLevel,
        orgRole: value.orgRole,
        name: value.name,
        rank: value.rank,
        isValidatedByCommander: value.isValidatedByCommander,
        isS2Admin: value.isS2Admin,
        email: value.email,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        principalId: value.principalId,
        registered: value.registered
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    deleted: boolean;
    subject: string;
    parentMessageId?: string;
    body: string;
    read: boolean;
    toUserId: Principal;
    sentAt: bigint;
    fromUserId: Principal;
}): {
    id: string;
    deleted: boolean;
    subject: string;
    parentMessageId: [] | [string];
    body: string;
    read: boolean;
    toUserId: Principal;
    sentAt: bigint;
    fromUserId: Principal;
} {
    return {
        id: value.id,
        deleted: value.deleted,
        subject: value.subject,
        parentMessageId: value.parentMessageId ? candid_some(value.parentMessageId) : candid_none(),
        body: value.body,
        read: value.read,
        toUserId: value.toUserId,
        sentAt: value.sentAt,
        fromUserId: value.fromUserId
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orgRole: string;
    name: string;
    rank: string;
    email: string;
    avatarUrl?: string;
}): {
    orgRole: string;
    name: string;
    rank: string;
    email: string;
    avatarUrl: [] | [string];
} {
    return {
        orgRole: value.orgRole,
        name: value.name,
        rank: value.rank,
        email: value.email,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentPermission): {
    Viewer: null;
} | {
    Editor: null;
} | {
    NoAccess: null;
} | {
    Owner: null;
} {
    return value == DocumentPermission.Viewer ? {
        Viewer: null
    } : value == DocumentPermission.Editor ? {
        Editor: null
    } : value == DocumentPermission.NoAccess ? {
        NoAccess: null
    } : value == DocumentPermission.Owner ? {
        Owner: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FolderPermission>): Array<_FolderPermission> {
    return value.map((x)=>to_candid_FolderPermission_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
